---
output_dir: "."
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

```{r load-data, message=FALSE}
library(tidyverse)
library(kableExtra)
library(rmarkdown)
library(ggpubr)

pop_data <- read_csv("data/gapminder_data.csv")

euro_data_tbl <- pop_data %>% 
                    filter(continent == "Europe" & year == 2007) %>% 
                    select(-continent, -year) %>% 
                    arrange(desc(lifeExp)) %>% 
                    rename(Country = country, "Population Size" = pop, 
                      "Life Expectancy" = lifeExp, "GDP" = gdpPercap)
```

The results in euro_data_tbl are displayed in the Table below

```{r Table , message=FALSE}

euro_data_tbl %>% 
          kbl() %>%
          kable_styling(bootstrap_options = c("striped", "hover","bordered","responsive"), 
                        full_width = F) %>% 
  scroll_box(width="100%", height = "400px")

```

This is a better way to display long tables

```{r paged-table}
paged_table(euro_data_tbl)
```

# Adding Images

```{r Plot , warning = FALSE}
euro_plot<-pop_data %>% 
        filter(continent == "Europe")  %>% 
        mutate(year=as_factor(year)) %>% 
  ggplot(aes(x = year, y= lifeExp)) +
  geom_violin()+
  stat_summary(fun.y = median, geom = "point")

euro_plot


```

```{r uk_plot}
uk_plot<-pop_data %>% 
        filter(country == "United Kingdom")  %>% 
        mutate(year=as_factor(year)) %>% 
  ggplot(aes(x = year, y= lifeExp)) +
  geom_point()+
  stat_summary(fun.y = median, geom = "point")

uk_plot

ggarrange(euro_plot, uk_plot, ncol = 2, nrow= 1, labels = "AUTO")

```







